gba copy/competition/urls.py
from django.conf.urls import patterns, url
from competition import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^New', views.new, name='new'),
                       url(r'^Insert', views.insert, name='insert'),
)

gba copy/gba/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gba.views.home', name='home'),
    # url(r'^gba/', include('gba.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^Team/', include('team.urls', namespace="team")),
    url(r'^Trade/', include('trade.urls', namespace="trade")),
    url(r'^Market/', include('market.urls', namespace="market")),
    url(r'^Competition/', include('competition.urls', namespace="competition")),
    url(r'^Match/', include('match.urls', namespace="match")),
    url(r'^admin/', include(admin.site.urls)),
)

gba copy/market/urls.py
from django.conf.urls import patterns, url
from market import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^new', views.new, name='new'),
                       url(r'^insert', views.insert, name='insert'),
)

gba copy/match/urls.py
from django.conf.urls import patterns, url
from match import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^New', views.new, name='new'),
                       url(r'^Insert', views.insert, name='insert'),
                       url(r'^Delete', views.delete, name='delete'),
)

gba copy/team/urls.py
from django.conf.urls import patterns, url
from team import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^new', views.new, name='new'),
                       url(r'^insert', views.insert, name='insert'),
)

gba copy/trade/urls.py
from django.conf.urls import patterns, url
from trade import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^New', views.new, name='new'),
                       url(r'^Insert', views.insert, name='insert'),
)

gba copy/competition/models.py
from django.db import models

# Create your models here.
from django.db.models.fields import CharField


class Competition(models.Model):
    competition_name = CharField(max_length=20)

    def __str__(self):
        return self.competition_name

gba copy/market/models.py
from django.db import models

# Create your models here.
from django.db.models.fields import CharField


class Market(models.Model):
    market_name = CharField(max_length=20)

    def __str__(self):
        return self.market_name

gba copy/match/models.py
from django.db import models
from team.models import Team
from competition.models import Competition

# Create your models here.

class Match(models.Model):
    competition = models.ForeignKey(Competition, related_name="competition")
    homeTeam = models.ForeignKey(Team, related_name="home")
    awayTeam = models.ForeignKey(Team, related_name="away")

    def __str__(self):
        return self.homeTeam.team_name + ' vs ' + self.awayTeam.team_name

gba copy/team/models.py
from django.db import models
from django.db.models.fields import CharField


class Team(models.Model):
    team_name = CharField(max_length=20)

    def __str__(self):
        return self.team_name

gba copy/trade/models.py
from django.db import models
from market.models import Market
from match.models import Match

class Trade(models.Model):
    match = models.ForeignKey(Match, related_name="match")
    market = models.ForeignKey(Market, related_name="market")
    invested = models.DecimalField(max_digits=5, decimal_places=2)
    profitLoss = models.DecimalField(max_digits=5, decimal_places=2)
    #dateTrade = models.DateTimeField()

    def __str__(self):
        return self.invested

    def divide(self):
        return (int(self.profitLoss) * 100) / int(self.invested)

gba copy/competition/views.py
# Create your views here.
from django.shortcuts import render
from django.template.context import RequestContext
from django.http import HttpResponseRedirect
from competition.models import Competition


def index(request):
    competitions = Competition.objects.all()
    context = RequestContext(request,
                             {'allCompetitions': competitions}
    )
    return render(request, 'competition/index.html', context)

def new(request):
    return render(request, 'competition/new.html', )

def insert(request):
    competition = Competition(competition_name = request.POST.get('competitionName'))

    #competition.competition_name = request.POST.get('competitionName')
    competition.save()
    #return render('teste')
    return HttpResponseRedirect('/Competition/')

gba copy/market/views.py
from django.shortcuts import render
from django.template.context import RequestContext
from market.models import Market


def index(request):
    allMarkets = Market.objects.all()
    context = RequestContext(request,
                             {'allMarkets': allMarkets}
    )
    return render(request, 'market/index.html', context)

def new(request):
    return render(request, 'market/new.html', )

def insert(request):
    market = Market(market_name = request.POST.get('marketName'))
    market.save()
    return render(request, 'market/new.html', )

gba copy/match/views.py
from django.shortcuts import render
from match.models import Match
from team.models import Team
from django.template.context import RequestContext
from competition.models import Competition
from django.http.response import HttpResponseRedirect

def index(request):
     matches = Match.objects.all()
     context = RequestContext(request, {'allMatches': matches})
     return render(request, 'match/index.html', context)

def new(request):
    teams = Team.objects.all()
    competitions = Competition.objects.all()
    context = RequestContext(request, {'allTeams': teams, 'allCompetitions': competitions,})
    return render(request, 'match/new.html',context )

def insert(request):
    if request.method == 'POST': # If the form has been submitted...
        postCompetition = Competition.objects.get(pk=request.POST["competition"])
        postHomeTeam= Team.objects.get(pk=request.POST["homeTeam"])
        postAwayTeam = Team.objects.get(pk=request.POST["awayTeam"])
        m = Match(
            competition = postCompetition, homeTeam = postHomeTeam, awayTeam = postAwayTeam)
        m.save()
    return HttpResponseRedirect('/Match/')

def delete(request):
    if request.method == 'POST': # If the form has been submitted...
        m = Match.objects.get(pk=request.POST["match"])
        m.delete()
    return HttpResponseRedirect('/Match/')

gba copy/team/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.template.context import RequestContext
from team.models import Team


def index(request):
    allTeams = Team.objects.all()
    context = RequestContext(request,
                             {'allTeams': allTeams}
    )
    return render(request, 'team/index.html', context)

def new(request):
    return render(request, 'team/new.html', )

def insert(request):
    if request.method == 'POST': # If the form has been submitted...
        t = Team(team_name=request.POST["teamName"])
        t.save()
        return HttpResponseRedirect('/Team/')

gba copy/trade/views.py
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render
from django.template.context import RequestContext
from trade.models import Trade
from trade.forms import TradeForm


def index(request):
    allTrades = Trade.objects.all()
    context = RequestContext(request, {'allTrades': allTrades})
    return render(request, 'trade/index.html', context)


def new(request):
    form = TradeForm()
    return render(request, 'trade/new.html', {'form': form})


@csrf_protect
def insert(request):
    if request.method == "POST":
        form = TradeForm(request.POST)
        if form.is_valid():
            post = form.save(commit= True)
            post.save()
            return render(request, 'trade/index.html', )
        else:
            return render(request, 'trade/new.html', {'form': form})
    else:
        form = TradeForm()
        return render(request, 'trade/new.html', {'form': form})

gba copy/competition/templates/competition/index.html
{% extends "gba_menu.html" %}

{% block screenMenu %}
<h1>Competition:</h1>
{% endblock %}
{% block content %}
<a href="{% url 'competition:new' %}">New competition</a>
<table>
    <tr>
        <td>Name</td>
        <td></td>
    </tr>
    {% for competition in allCompetitions %}
    <tr>
        <td>{{ competition.competition_name }}</td>
        <td><a href="{% url 'market:index' %}"><span class="glyphicon glyphicon-remove" style="cursor: pointer;"></span></a>
        </td>
    </tr>
    {% endfor %}

</table>
{% endblock %}

gba copy/competition/templates/competition/new.html
{% extends "gba_menu.html" %}

{% block screenMenu %}
<h1>Competition:</h1>
{% endblock %}
{% block content %}
<h1>Insert new Competition</h1>
<form method="post" action="{% url 'competition:insert' %}">
    {% csrf_token %}
    <input name="competitionName">
    <input type="submit" value="Add new competition!"></input>
</form>
{% endblock %}

gba copy/market/templates/market/index.html
{% extends "gba_menu.html" %}

{% block screenMenu %}
<h1>Market:</h1>
{% endblock %}
{% block content %}
<a href="{% url 'market:new' %}"> Create new market</a><br>
<h4>All markets untill date</h4>
<table>
{% for market in allMarkets %}
    <tr>
        <td> {{ market.market_name }} </td>
        <td ><a href="{% url 'market:index' %}"><span class="glyphicon glyphicon-remove" style="cursor: pointer;"></span></a></td>
    </tr>
{% endfor %}
{% endblock %}

gba copy/market/templates/market/new.html
{% extends "gba_menu.html" %}

{% block screenMenu %}
<h1>Market:</h1>
{% endblock %}
{% block content %}
<h1>Insert new Market</h1>
<form method="post" action="{% url 'market:insert' %}">
    {% csrf_token %}
    <input name="marketName">
    <input type="submit" value="Add new Market!"></input>
</form>
{% endblock %}

gba copy/match/templates/match/index.html
{% extends "gba_menu.html" %}
{% block screenMenu %}
<h1>Match:</h1>
{% endblock %}
{% block content %}
<a href="{% url 'match:new' %}"> Create new match</a><br>
<h4> Matches until date:</h4>
<div class="container-fluid col-md-8 ">
    <table class="table col-md-offset-1">
        <tr>
            <td>Competition</td>
            <td>Home Team</td>
            <td></td>
            <td>Away Team</td>
            <td>Date</td>
            <td></td>
        </tr>
        {% for match in allMatches %}
        <form action="{% url 'match:delete' %}" method="post" id="teste">
            {% csrf_token %}
            <input type="hidden" value="{{ match.id }}" id="match" name="match">
            <tr>
                <td>{{ match.competition.competition_name }}</td>
                <td>{{ match.homeTeam }}</td>
                <td> vs</td>
                <td>{{ match.awayTeam}}</td>
                <td>(Em construição)</td>
                <td><span class="glyphicon glyphicon-remove" style="cursor: pointer;" onclick="document.getElementById('match').value = {{ match.id }};document.getElementById('teste').submit();"></span></td>
            </tr>
        </form>
</div>
{% endfor %}
{% endblock %}

gba copy/match/templates/match/new.html
{% extends "gba_menu.html" %}

{% block screenMenu %}
<h1>Match</h1>
{% endblock %}
{% block content %}

<h1>Insert new Match</h1>
<form method="post" action="{% url 'match:insert' %}">
    {% csrf_token %}

    <h4>Select Competition:</h4>
     <select name="competition">
        {% for competition in allCompetitions %}
        <option value="{{ competition.id }}"> {{ competition.competition_name }} </option>
        {% endfor %}
    </select>

    <h4>Select home team:</h4>
     <select name="homeTeam">
        {% for team in allTeams %}
        <option value="{{ team.id }}"> {{ team.team_name }} </option>
        {% endfor %}
    </select>

    <h4>Select away team:</h4>
    <select name="awayTeam">
        {% for team in allTeams %}
        <option value="{{ team.id }}"> {{ team.team_name }} </option>
        {% endfor %}
    </select>

    <h4>Insert match date (format: dd-mm-YYYY):</h4>
    <input type="text">

    <input type="submit" value="Add new match!">
</form>
{% endblock %}

gba copy/team/templates/team/index.html
{% extends "gba_menu.html" %}

{% block screenMenu %}
<h1>Teams</h1>
{% endblock %}
{% block content %}

<a href="{% url 'team:new' %}"> Create new team</a><br>
<h4>Teams until date:</h4>
<table>
    <tr>
        <td></td>
        <td></td>
    </tr>
{% for team in allTeams %}
    <tr>
        <td> {{ team.team_name }}</td>
        <td ><a href="{% url 'team:index' %}"><span class="glyphicon glyphicon-remove" style="cursor: pointer;"></span></a></td>
    </tr>
{% endfor %}
</table>
{% endblock %}

gba copy/team/templates/team/new.html
{% extends "gba_menu.html" %}

{% block screenMenu %}
<h1>Insert new Team</h1>
{% endblock %}
{% block content %}

<form method="post" action="{% url 'team:insert' %}">
    {% csrf_token %}
    <input name="teamName">
    <input type="submit" value="Add new Team!"></input>
</form>
{% endblock %}

gba copy/templates/gba_menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" />
    <!--<title>{% block title %}My amazing site{% endblock %}</title>-->
</head>

<body>
<a href="{% url 'competition:index' %}">Competitions</a>
<a href="{% url 'team:index' %}">Teams</a>
<a href="{% url 'trade:index' %}">Trades</a>
<a href="{% url 'market:index' %}">Markets</a>
<a href="{% url 'match:index' %}">Match</a>

<div>
    <h1>{% block screenMenu %}{% endblock %}</h1>
</div>
        {% block content %} {% endblock %}
</body>
</html>

gba copy/trade/templates/trade/index.html
{% extends "gba_menu.html" %}

{% block screenMenu %}
<h1>Trades</h1>
{% endblock %}
{% block content %}

<a href="{% url 'trade:new' %}"> Create new trade</a><br>
<table class="table">
    <tr>
        <td>Match</td>
        <td>Invested</td>
        <td>Profit & Loss</td>
        <td>ROI</td>
        <td></td>
    </tr>

    {% for trade in allTrades %}
    <tr id="{{trade.id}}">
        <td>{{trade.match}}</td>
        <td>{{trade.market}}</td>
        <td>{{trade.invested}}€</td>
        <td>{{trade.profitLoss}}€</td>
        <td>{{ trade.divide }}%</td>
        <td><a href="{% url 'trade:index' %}"><span class="glyphicon glyphicon-remove" style="cursor: pointer;"></span></a>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

gba copy/trade/templates/trade/new.html
{% extends "gba_menu.html" %}

{% block screenMenu %}
<h1>Trades</h1>
{% endblock %}

{% block content %}
<h1>Insert new trade</h1>
<form method="POST" class="post-form" action="{% url 'trade:insert' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Add new trade!</button>
</form>


{% endblock %}